# Generated by Django 5.0.6 on 2024-06-04 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField()),
                ('shipping_country_code', models.CharField(max_length=10)),
                ('shipping_zipcode', models.CharField(max_length=20)),
                ('shipping_city', models.CharField(max_length=100)),
                ('shipping_number', models.CharField(max_length=100)),
                ('shipping_street', models.CharField(max_length=255)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('price_incl', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
