# Generated by Django 5.0.6 on 2024-06-23 05:40

import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_title', models.CharField(max_length=255)),
                ('product_title', models.CharField(max_length=255)),
                ('variant_title', models.CharField(max_length=255)),
                ('quantity_ordered', models.IntegerField()),
                ('article_code', models.CharField(max_length=100)),
                ('ean', models.CharField(max_length=100)),
                ('sku', models.CharField(max_length=100)),
                ('price_excl', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_incl', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product_url', models.URLField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_products', to='product.product')),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('number', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(choices=[('on_hold', 'On_hold'), ('processing_awaiting_payment', 'Processing_awaiting_payment'), ('processing_awaiting_shipment', 'Processing_awaiting_shipment'), ('processing_awaiting_pickup', 'Processing_awaiting_pickup'), ('processing_ready_for_pickup', 'Processing_ready_for_pickup'), ('completed', 'Completed'), ('completed_shipped', 'Completed_shipped'), ('completed_picked_up', 'Completed_picked_up'), ('cancelled', 'Cancelled')], max_length=50)),
                ('channel', models.CharField(choices=[('api', 'API'), ('main', 'Main')], max_length=10)),
                ('created_at', models.DateTimeField()),
                ('price_incl', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_excl', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_status', models.CharField(choices=[('not_paid', 'Not_paid'), ('partially_paid', 'Partially_paid'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], max_length=30)),
                ('firstname', models.CharField(blank=True, max_length=50, null=True)),
                ('lastname', models.CharField(blank=True, max_length=50, null=True)),
                ('addressShippingStreet', models.CharField(blank=True, max_length=100, null=True)),
                ('addressShippingNumber', models.CharField(blank=True, max_length=20, null=True)),
                ('addressShippingExtension', models.CharField(blank=True, max_length=10, null=True)),
                ('addressShippingZipcode', models.CharField(blank=True, max_length=20, null=True)),
                ('addressShippingCity', models.CharField(blank=True, max_length=100, null=True)),
                ('shipping_country_code', models.CharField(max_length=3)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('customer_URL', models.CharField(max_length=250)),
                ('products_URL', models.CharField(max_length=250)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='customer.customer')),
                ('products', models.ManyToManyField(through='sales.OrderProduct', to='product.product')),
            ],
            options={
                'ordering': ('-created_at',),
            },
            managers=[
                ('webshopObjects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_products', to='sales.orders'),
        ),
    ]
