# Generated by Django 5.0.6 on 2024-06-23 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='orders',
            managers=[
            ],
        ),
    ]
